# URL no formato JDBC correto
spring.datasource.url=${DB_URL}

# Usuário e senha passados separadamente
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configurações adicionais
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver