# Use a URL completa. O Spring Boot extrai o usuário e senha daqui.
spring.datasource.url=${DATABASE_URL}

# Configurações adicionais
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver